---
abstract: 'Catalyst based application'
author:
  - 'System Administrator'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: '0.88'
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.16'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AddressBook
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Action::RenderView: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::Session::Store::DBIC: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Runtime: '5.90103'
  Config::General: 0
  Config::JFDI: '0.065'
  Moose: 0
  Text::CSV_XS: '1.2'
  namespace::autoclean: 0
resources:
  license: http://dev.perl.org/licenses/
version: '0.01'
